module Main where

import Control.Exception
import Day1

main = catch toTry handler
